CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS otp (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    userId UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code VARCHAR(6) NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    isUsed BOOLEAN DEFAULT FALSE,
    ip inet NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);